name: 'setup-ada'
description: 'Setup and Ada development environment'
author: 'AdaCore'
inputs:
  distrib:
    description: 'GNAT distribution (fsf or community)'
    default: 'fsf'
  target:
    description: 'Target architecture (native, arm-elf, riscv32-elf)'
    default: 'native'
  community_year:
    description: 'Year of the community release (2019)'
    default: '2019'
runs:
  using: 'node12'
  main: 'lib/main.js'
